queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    merge_conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    merge_method: merge
    update_method: rebase

pull_request_rules:
  - name: remove outdated approved reviews
    conditions:
      - author!=@core
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: |
          Approving reviews have been dismissed because this pull request
          was updated.
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
