kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: flux-coral2
# patch the generated kubeadm config with settings to enable access from within docker
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: host.docker.internal
