apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nearnodeflashes.rabbit.hpe.com
spec:
  group: rabbit.hpe.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                status:
                  type: string
                percentDegraded:
                  type: number
                allocationGranularityUnits:
                  type: string
                allocationGranularity:
                  type: number
                capacityUnits:
                  type: string
                capacity:
                  type: number
                computes:
                  type: array 
                  items: 
                    type: string
  scope: Namespaced
  names:
    plural: nearnodeflashes
    singular: nearnodeflash
    kind: NearNodeFlash
    shortNames:
    - nnf
